import next from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link" 

export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Zephyr Picture Map | Burlington Adventures!</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/faviconn.ico" />
          <script src="https://d3js.org/d3.v5.min.js"></script>
  
          </Head>
  
        <main className={styles.main}>
            <img src={'/VT Photos/VERMONT1.jpg'} />
            <br/>
            <img src={'/VT Photos/VERMONT2.jpeg'} />
            <br/>
            <img src={'/VT Photos/VERMONT3.jpg'} />
            <br/>
            <img src={'/VT Photos/VERMONT4.jpg'} />
            <br/>
            <img src={'/VT Photos/VERMONT5.jpg'} />
            <br/>
            <img src={'/VT Photos/VERMONT6.jpg'} />
            <br/>
            <img src={'/VT Photos/VERMONT7.jpg'} />
            <br/>
            <img src={'/VT Photos/VERMONT8.jpg'} />
            <br/>
            <img src={'/VT Photos/VERMONT9.jpeg'} />
            <br/>
            <img src={'/VT Photos/VERMONT10.jpg'} />
            <br/>
        </main>

    </div>
    )
}

