import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Zephyr Picture Map | LA Adventures!</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/faviconn.ico" />
          <script src="https://d3js.org/d3.v5.min.js"></script>
  
          </Head>
  
        <main className={styles.main}>
            <img src={'/LA Photos/LA1.jpeg'} />
            <br/>
            <img src={'/LA Photos/LA2.jpeg'} />
            <br/>
            <img src={'/LA Photos/LA3.jpg'} />
            <br/>
            <img src={'/LA Photos/LA4.jpg'} />
            <br/>
            <img src={'/LA Photos/LA5.jpg'} />
            <br/>
            <img src={'/LA Photos/LA6.jpg'} />
            <br/>
            <img src={'/LA Photos/LA7.jpg'} />
            <br/>
            <img src={'/LA Photos/LA8.jpg'} />
            <br/>
            <img src={'/LA Photos/LA9.jpg'} />
            <br/>
            <img src={'/LA Photos/LA10.png'} />
            <br/>

        </main>

    </div>
    )
}

