import next from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"

export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Zephyr Picture Map | NYC Adventures!</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/faviconn.ico" />
          <script src="https://d3js.org/d3.v5.min.js"></script>
  
          </Head>
  
        <main className={styles.main}>
            <img src={'NYC Photos/NYC1.jpeg'} />
            <br/>
            <img src={'/NYC Photos/NYC2.jpeg'} />
            <br/>
            <img src={'/NYC Photos/NYC3.jpg'} />
            <br/>
            <img src={'/NYC Photos/NYC4.jpg'} />
            <br/>
            <img src={'/NYC Photos/NYC5.jpeg'} />
            <br/>
            <img src={'/NYC Photos/NYC6.jpg'} />
            <br/>
            <img src={'/NYC Photos/NYC7.jpg'} />
            <br/>
            <img src={'/NYC Photos/NYC8.jpg'} />
            <br/>
            <img src={'/NYC Photos/NYC9.jpeg'} />
            <br/>
            <img src={'/NYC Photos/NYC10.jpg'} />
            <br/>
        </main>

    </div>
    )
}

