import next from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"


export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Zephyr Picture Map | LA Adventures!</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/faviconn.ico" />
          <script src="https://d3js.org/d3.v5.min.js"></script>
  
          </Head>

        <header>
        <Link href = "/pics"><a style = {{
          padding: "5px", 
          border: "1px solid red",
          borderRadius: "5px",
          left: "1vw",
          top: "1vh",
          position: "absolute"
          }}>Location Directory</a></Link>
        </header>
  
        <main className={styles.main}>

            <img src={'/LA Photos/LA1.jpeg'} />
            <br/>
            <img src={'/LA Photos/LA2.jpeg'} />
            <br/>
            <img src={'/LA Photos/LA3.jpg'} />
            <br/>
            <img src={'/LA Photos/LA4.jpg'} />
            <br/>
            <img src={'/LA Photos/LA5.jpg'} />
            <br/>
            <img src={'/LA Photos/LA6.jpg'} />
            <br/>
            <img src={'/LA Photos/LA7.jpg'} />
            <br/>
            <img src={'/LA Photos/LA8.jpg'} />
            <br/>
            <img src={'/LA Photos/LA9.jpg'} />
            <br/>
            <img src={'/LA Photos/LA10.png'} />
            <br/>

        </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/lavanya-sharma/zephyrmaps/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with 🚂 and ❤️
        </a>
      </footer>     

    </div>
    )
}

