import next from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"

export default function Home() {
    return (

      <div className={styles.container}>

        <Head>
          <title>Zephyr Picture Map | Locations</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/faviconn.ico" />
          <script src="https://d3js.org/d3.v5.min.js"></script>
        </Head>

        <header>
        <Link href = "/"><a style = {{
          padding: "5px", 
          border: "1px solid red",
          borderRadius: "5px",
          left: "1vw",
          top: "1vh",
          position: "absolute"
          }}>Home</a></Link>
        </header>

        <main>

        <Link href = "/burlington" ><a style = {{
        padding: "5px", 
        border: "1px solid red",
        borderRadius: "5px"
        }}>Burlington, VT</a></Link>
        <br/>
        <br/>
        <br/>

        <Link href = "/nyc" ><a style = {{
        padding: "5px", 
        border: "1px solid red",
        borderRadius: "5px"
        }}>New York City, NY</a></Link>

        <br/>
        <br/>
        <br/>
        <Link href = "/chicago" ><a style = {{
        padding: "5px", 
        border: "1px solid red",
        borderRadius: "5px"
        }}>Chicago, IL</a></Link>
        
        <br/>
        <br/>
        <br/>
        <Link href = "/sf" ><a style = {{
        padding: "5px", 
        border: "1px solid red",
        borderRadius: "5px"
        }}>San Francisco, CA</a></Link>
        
        <br/>
        <br/>
        <br/>
        <Link href = "/la" ><a style = {{
        padding: "5px", 
        border: "1px solid red",
        borderRadius: "5px"
        }}>Los Angeles, CA</a></Link>

        </main>

    
        <footer className={styles.footer} 
        style = {{position: "fixed", bottom: "0"}}
        >
        <a
          href="https://github.com/lavanya-sharma/zephyrmaps/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with 🚂 and ❤️
        </a>
      </footer>

    </div>
  )
}
